#First Progress
line = "="*50 #membuat garis dengan panjang 50 karakter
title = "{:^50}".format("input data siswa".upper()) #judul input
print(line)
print(title)
print(line)
dataJumlah = input("Berapa Jumlah Siswa yang akan di input? [1/3/5] : " +str()) #Bertanya jumlah data yang akan di input pilihan jumlah data yang bisa di input 1/3/5

if dataJumlah == "1" : #Fungsi ini akan di eksekusi Jika jumlah data yang di input 1
    line = "="*50
    print(line)
    name = input("Masukkan Nama : " +str())
    kelas = input("Masukkan Kelas : " +str())
    jurusan = input("Masukkan Jurusan : " +str())
    print(line)
    print("Hasil Input")
    print("Nama Siswa : " +name)
    print("Nama Kelas : " +kelas)
    print("Nama Jurusan : " +jurusan)
    print(line)
elif dataJumlah == "3": #Fungsi ini akan di eksekusi Jika jumlah data yang di input 3
    line = "="*50
    print(line)
    name = input("Masukkan Nama : " +str())
    kelas = input("Masukkan Kelas : " +str())
    jurusan = input("Masukkan Jurusan : " +str())
    print(line)
    name2 = input("Masukkan Nama : " +str())
    kelas2 = input("Masukkan Kelas : " +str())
    jurusan2 = input("Masukkan Jurusan : " +str())
    print(line)
    name3 = input("Masukkan Nama : " +str())
    kelas3 = input("Masukkan Kelas : " +str())
    jurusan3 = input("Masukkan Jurusan : " +str())
    print(line)
    jumlahStruk = input("Berapa Struk yang dicetak? [1/2/3]: " +str())
    if jumlahStruk == "1":
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name)
        print("Nama Kelas : " +kelas)
        print("Nama Jurusan : " +jurusan)
        print(line)
    elif jumlahStruk == "2":
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name)
        print("Nama Kelas : " +kelas)
        print("Nama Jurusan : " +jurusan)
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name2)
        print("Nama Kelas : " +kelas2)
        print("Nama Jurusan : " +jurusan3)
        print(line)
    elif jumlahStruk == "3":
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name)
        print("Nama Kelas : " +kelas)
        print("Nama Jurusan : " +jurusan)
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name2)
        print("Nama Kelas : " +kelas2)
        print("Nama Jurusan : " +jurusan3)
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name3)
        print("Nama Kelas : " +kelas3)
        print("Nama Jurusan : " +jurusan3)
        print(line)
    else:
        print("you stupid".upper())
elif dataJumlah == "5": #Fungsi ini akan di eksekusi Jika jumlah data yang di input 5
    line = "="*50
    print(line)
    name = input("Masukkan Nama : " +str())
    kelas = input("Masukkan Kelas : " +str())
    jurusan = input("Masukkan Jurusan : " +str())
    print(line)
    name2 = input("Masukkan Nama : " +str())
    kelas2 = input("Masukkan Kelas : " +str())
    jurusan2 = input("Masukkan Jurusan : " +str())
    print(line)
    name3 = input("Masukkan Nama : " +str())
    kelas3 = input("Masukkan Kelas : " +str())
    jurusan3 = input("Masukkan Jurusan : " +str())
    print(line)
    name4 = input("Masukkan Nama : " +str())
    kelas4 = input("Masukkan Kelas : " +str())
    jurusan4 = input("Masukkan Jurusan : " +str())
    print(line)
    name5 = input("Masukkan Nama : " +str())
    kelas5 = input("Masukkan Kelas : " +str())
    jurusan5 = input("Masukkan Jurusan : " +str())
    print(line)
    jumlahStruk = input("Berapa Struk yang dicetak? [1/2/3/4/5]: " +str())
    if jumlahStruk == "1":
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name)
        print("Nama Kelas : " +kelas)
        print("Nama Jurusan : " +jurusan)
        print(line)
    elif jumlahStruk == "2":
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name)
        print("Nama Kelas : " +kelas)
        print("Nama Jurusan : " +jurusan)
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name2)
        print("Nama Kelas : " +kelas2)
        print("Nama Jurusan : " +jurusan3)
        print(line)
    elif jumlahStruk == "3":
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name)
        print("Nama Kelas : " +kelas)
        print("Nama Jurusan : " +jurusan)
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name2)
        print("Nama Kelas : " +kelas2)
        print("Nama Jurusan : " +jurusan3)
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name3)
        print("Nama Kelas : " +kelas3)
        print("Nama Jurusan : " +jurusan3)
        print(line)
    elif jumlahStruk == "4":
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name)
        print("Nama Kelas : " +kelas)
        print("Nama Jurusan : " +jurusan)
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name2)
        print("Nama Kelas : " +kelas2)
        print("Nama Jurusan : " +jurusan3)
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name3)
        print("Nama Kelas : " +kelas3)
        print("Nama Jurusan : " +jurusan3)
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name4)
        print("Nama Kelas : " +kelas4)
        print("Nama Jurusan : " +jurusan4)
        print(line)
    elif jumlahStruk == "4":
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name)
        print("Nama Kelas : " +kelas)
        print("Nama Jurusan : " +jurusan)
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name2)
        print("Nama Kelas : " +kelas2)
        print("Nama Jurusan : " +jurusan3)
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name3)
        print("Nama Kelas : " +kelas3)
        print("Nama Jurusan : " +jurusan3)
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name4)
        print("Nama Kelas : " +kelas4)
        print("Nama Jurusan : " +jurusan4)
        print(line)
        print("Hasil Input")
        print("Nama Siswa : " +name5)
        print("Nama Kelas : " +kelas5)
        print("Nama Jurusan : " +jurusan5)
        print(line)
    else:
        print("you stupid".upper())
else:
    print("you stupid".upper()) #Fungsi ini akan di eksekusi Jika jumlah data yang di input selain pilihan yang di sediakan
